### ISSUE TITLE
Remove categories out of order.

### ISSUE THREAD

**Issue by Smidra** [Smidra/datoun-admin#6]
Just like with aliases. with the little minus...

![image](https://user-images.githubusercontent.com/25660869/205163462-3a29a8ed-68e3-4462-b5e0-5df992bbe831.png)

![betterpic](https://user-images.githubusercontent.com/25660869/205501202-0ef1fed5-3631-4acb-a004-e95675b90b40.png)
de5-9bb9-4fd8-a7b0-1a28af2799d7.png)

**Comment by Smidra** [comment]
Fixed in c6397d27fd258ce0da2d13039d5d9abc0ccce93d

**Comment by jindrazak** [comment]
I guess we are good with this one fixed by https://github.com/Smidra/datoun-admin/pull/15
